### ISSUE TITLE
add legend to road_crossings_map.png

### ISSUE THREAD

**Issue by sarahcd** [movestore/Y2Y_road_interaction#1]
Add a legend indicating the red (Tracks), yellow (Crossings) and blue (Roads). 
Also, I see the roads displayed as a "Road property" with a color gradient for values 2-4. Is this intended?

**Comment by andreakoelzsch** [comment]
Hi Sarah, I have tried to add the tracks and crossings to the legend, much time later I have to stop and do other things. I have adapted the title and made the road property discrete classes rather than a gradient. hope to make a new version soon.
