### ISSUE TITLE
Bug with animal IDs with numbers?

### ISSUE THREAD

**Issue by abcour01** [movestore/Y2Y_road_interaction#11]
Hi Andrea, we talked about this today. Reporting it here for you. There seems to be an issue with this app when my animal IDs in Movebank are numbers like "55". The app renamed this animal to "X55" which caused errors. Here is are some screenshots. Thanks! Aly

![error screenshot](https://user-images.githubusercontent.com/131817404/234400143-420d4bac-0a18-456b-93d8-48243bee9cfe.jpg)

![movebank data screenshot](https://user-images.githubusercontent.com/131817404/234400760-fececd0c-f7b5-4490-b76a-30ce2f3b04f3.jpg)

**Comment by andreakoelzsch** [comment]
HI @abcour01 thanks for the message and for posting it here :) Please, could you post me here or send via Email (akoelzsch@ab.mpg.de) the rds file that came out of the APp before the one with the error? THanks!

**Comment by andreakoelzsch** [comment]
THanks for the help @abcour01, this is fixed now and running on MOveApps. Please try it out and let me know if it does not work. :)
