### ISSUE TITLE
Error after converting Move2_loc to moveStack

### ISSUE THREAD

**Issue by RobinMov** [movestore/Y2Y_road_interaction#17]
The error 'Error in FUN(X[[i]], ...): !anyNA(x) is not TRUE' is returned after using the Move2_loc to moveStack app in an updated version of the Assess Road Interactions workflow that I have been working on. I have done my best to eliminate user error as a cause, but I cannot be certain.

Here is an image of the logs after the app has run and returned the error:
![Screenshot 2024-04-24 134421](https://github.com/movestore/Y2Y_road_interaction/assets/124919528/1cd576d1-6912-4057-977e-b3d294a9ec4d)

**Comment by andreakoelzsch** [comment]
solved by transfer to move2
