### ISSUE TITLE
add background map to road_crossings_map.png

### ISSUE THREAD

**Issue by sarahcd** [movestore/Y2Y_road_interaction#2]
Here a background layer could be helpful, especially if it includes infrastructure info. This could help the user assess whether the input roads layer they used for the analysis may be missing other important infrastructure. I'm not sure which background layers are compatible with this plot, but one good option is OpenStreetMap.Mapnik (see https://leaflet-extras.github.io/leaflet-providers/preview/)

**Comment by andreakoelzsch** [comment]
for using the leaflet maps, I would have to completely rework the App, which is not worth it now before switching to sf/move2. Sorry, if a background map is needed, then best go with the leaflet App for now. I will add this suggestion for the next major version of this app.
