### ISSUE TITLE
review alignment of GRIP roads

### ISSUE THREAD

**Issue by sarahcd** [movestore/Y2Y_road_interaction#6]
Plotting the identified road crossings on leaflet (red points on the right), it looks like the apparent road (from the GRIP database) is slightly to the east of the roads as shown on the background maps. The background maps seem to be correct. Here are the same animal occurrences in the Event Editor (left) and shown on a leaflet map along with the identified road crossings (right). I'll share the workflow with you. Can you check whether this might be due to inaccuracy in the original GRIP database or something about how the app is reading the data or calculating intersections?

<img width="1283" alt="image" src="https://user-images.githubusercontent.com/15783614/230656885-df4615a8-4a9d-4092-9fa7-3f999e71fd4b.png">

**Comment by andreakoelzsch** [comment]
Hi Sarah, this really is a difficult one. Great that you checked it with the leaflet map.
One thing could have made a diffierence is that the projection of the road intersection points may not have been in the same projection as the tracking data and the map. I have double-checked and adapted this, but it seems not to make a difference.
Further, what I find rather strange is that the png plot shows nice overlap of the intersections with the red road line. In this data set there is only one road of property 2 (primary road, but no highway, does that fit?).
According to your findings with another roads shapefile, I would say that indeed here the GRIP data set it not correct. It might be worth to look at the GRIP shapefile on top of some map. Is that possible on QGIS? THen, we could adapt the documentation in that respect.

**Comment by andreakoelzsch** [comment]
![leaflet_road_crossings](https://user-images.githubusercontent.com/65662928/232472030-868baae8-2480-4756-9002-88dcf6d766bf.jpg)

**Comment by sarahcd** [comment]
Thanks for checking. In this case I think the app is working correctly, and GRIP is just not that accurate. The GRIP documentation explains that the dataset is for 'global environmental and biodiversity modelling projects. The dataset is not suitable for navigation.' There are some options from [NaturalEarthData](https://www.naturalearthdata.com/downloads/10m-cultural-vectors/) that in my first tests are a bit better, but I think for detailed roads analysis people will need navigation-quality products.

**Comment by andreakoelzsch** [comment]
Hi @sarahcd and @annescharf, Anne and me have looked at this App very closely again today, because the map looked so much like projection errors to Anne. We have reworked everything, the App is updated, but still there is the alignment problem. So, it must be that the data set is not good enough.
![grafik](https://user-images.githubusercontent.com/65662928/233065554-dac1fbc4-7856-4be9-84f6-48977386d057.png)

**Comment by annescharf** [comment]
Hi @sarahcd and @andreakoelzsch I got curious so I just had a look in qgis what could be going wrong. I seems to be the road shp that is not perfect. In some places it matches, and in others it does not. The brown-orange lines is the shp.
![road1](https://user-images.githubusercontent.com/50947731/233198422-6ca7fc6c-53e8-4765-a94d-a137a0ca3359.png)
![roads2](https://user-images.githubusercontent.com/50947731/233198508-51bced53-f2a5-400c-9f5d-91e20591a3a7.png)
